name: Deploy to OVH via SFTP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ssh.cluster100.hosting.ovh.net
          port: 22
          username: ${{ secrets.OVH_FTP_USERNAME }}
          password: ${{ secrets.OVH_FTP_PASSWORD }}
          local_path: ./
          remote_path: /www/
          args: "-o StrictHostKeyChecking=no"
