name: Deploy to OVH via FTPS

on:
  push:
    branches: [ main ]   # si ta branche par défaut est "master", remplace par master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.OVH_FTP_SERVER }}
          username: ${{ secrets.OVH_FTP_USERNAME }}
          password: ${{ secrets.OVH_FTP_PASSWORD }}
          protocol: ftps
          port: 21
          server-dir: /www/
          local-dir: ./
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/.DS_Store
          log-level: standard
